# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  ecommerce-postgresql:
    image: postgres:14.2
    volumes:
      - ./.postgres-data-tests:/var/lib/postgresql/data
      - ./data/01-start.sql:/docker-entrypoint-initdb.d/01-start.sql
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=ecommerce
      - POSTGRES_PASSWORD=ecommerce
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
